"""Outbound webhook subscription + delivery models (Phase γ-B-2).

Outbound webhooks turn the worker's existing audit events into HTTP
notifications so operators don't have to poll for state changes (the
canonical case being ``task.awaiting_approval`` — without a webhook,
the human-in-the-loop story devolves into ad-hoc task polling, which
doesn't survive a real reviewer's day).

Two aggregates cohabit here:

* :class:`WebhookSubscription` — the operator-supplied "where to
  notify and what to notify on" config. Per-tenant.
* :class:`WebhookDelivery` — one attempt to push one event to one
  subscription. Carries its own payload copy (no FK into
  ``audit_events``) so the dispatcher can survive audit log
  rotation / archival without losing deliveries in flight.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class WebhookDeliveryStatus(StrEnum):
    """Lifecycle of a single delivery row.

    * ``PENDING`` — newly enqueued or scheduled for retry; the
      dispatcher will claim it when ``next_attempt_at <= now``.
    * ``DISPATCHED`` — terminal success; the subscriber returned
      a 2xx response.
    * ``DEAD_LETTER`` — terminal failure; the dispatcher exhausted
      the retry budget. Operators audit these and decide whether to
      requeue manually.
    """

    PENDING = "pending"
    DISPATCHED = "dispatched"
    DEAD_LETTER = "dead_letter"


class WebhookSubscription(BaseModel):
    """A tenant's "POST these events to this URL" config.

    ``events`` is a list of action strings (``task.awaiting_approval``,
    ``task.succeeded``, etc.) the subscription is interested in. The
    fanout step uses prefix-free exact matching: the subscription is
    notified iff ``audit.action in subscription.events``.

    ``secret`` is the HMAC signing key. It is never logged and never
    surfaced over the API; only the dispatcher reads it. Generated by
    the operator at subscription-creation time.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    subscription_id: str = Field(..., min_length=1)
    tenant_id: str = Field(..., min_length=1)
    url: str = Field(..., min_length=1, max_length=2048)
    secret: str = Field(..., min_length=8, max_length=512)
    events: tuple[str, ...] = Field(..., min_length=1)
    active: bool = True
    created_at: datetime


class WebhookDelivery(BaseModel):
    """One queued / in-flight / terminal HTTP push.

    ``payload`` is a JSON-safe snapshot of the event that produced
    this delivery (carved from the audit row at fanout time). The
    dispatcher signs ``payload`` with the subscription's secret and
    POSTs the rendered JSON to ``url`` (resolved through
    ``subscription_id`` at dispatch time, so a deactivated
    subscription stops driving new attempts on its existing rows).

    Retry semantics:

    * ``attempts`` is incremented on every dispatch attempt
      (successful and failed alike); after the configured cap the
      row terminates as ``DEAD_LETTER``.
    * ``next_attempt_at`` is the earliest moment the dispatcher will
      re-pick a ``PENDING`` row; an exponential backoff helper sets
      it on each failure.
    * ``idempotency_key`` is forwarded as ``X-Meta-Agent-Idempotency``
      so subscribers can dedupe their own state machines under retry.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    delivery_id: str = Field(..., min_length=1)
    subscription_id: str = Field(..., min_length=1)
    tenant_id: str = Field(..., min_length=1)
    trace_id: str = Field(..., min_length=1)
    event_action: str = Field(..., min_length=1)
    payload: dict[str, Any] = Field(default_factory=dict)
    idempotency_key: str = Field(..., min_length=1)
    status: WebhookDeliveryStatus = WebhookDeliveryStatus.PENDING
    attempts: int = Field(default=0, ge=0)
    next_attempt_at: datetime
    last_error: str | None = None
    created_at: datetime
    dispatched_at: datetime | None = None
